[package]
name = "sr_02_line"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.18.0"
minifb = "0.20"
image = "0.25.2"
winit = "0.28"
rodio = "0.17"